---
- name: Check protobuf version
  shell: "protoc --version"
  register: protoc_version
  changed_when: false
  ignore_errors: yes

# TODO: make more flexible by comparing version
- include: protobuf.yml
  when: protoc_version.failed is defined