---
- name: "Download protobuf {{ protobuf_version }} library"
  get_url:
    url: "{{ protobuf_url }}"
    dest: /tmp

- name: "Unarchive downloaded protobuf file"
  unarchive:
    src: /tmp/protobuf-cpp-{{ protobuf_version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: "Install protobuf libs"
  shell: "./configure && make -j4 && make install && ldconfig"
  args:
    chdir: "/opt/protobuf-{{ protobuf_version }}"
