---
- name: Create build directory
  file:
    state: directory
    dest: "{{ build_dir }}"
    owner: vagrant 
    group: vagrant

- name: Run cmake on project
  command: "cmake .."
  args:
    chdir: "{{ build_dir }}"
    changes: "{{ build_dir }}/*"

- name: Run make on project
  make:
    chdir: "{{ build_dir }}"
    target: all
    params:
      NUM_THREADS: 2