sudo: required

language: bash

services:
- docker

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push brandonsoto/videostream:server;
    docker push brandonsoto/videostream:client;
  fi

script:
- docker build -t brandonsoto/videostream:server -f server/Dockerfile .;
- docker run --rm --privileged multiarch/qemu-user-static:register --reset && docker build -t brandonsoto/videostream:client -f client/Dockerfile .;
