sudo: required

language: bash

services:
  - docker

script:
  - docker build -f server/Dockerfile
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f client/Dockerfile