version: "2"

services:
  server:
    build: server/
    ports:
      - "5555:5555"
    volumes:
      - .:/videostream-share

  client:
    build: client/
    ports:
      - "5555:5555"
    devices:
      - "/dev/vchiq"
      - "/dev/gpiomem"
    privileged: true
    volumes:
       - .:/videostream-share
