---
- name: Install docker dependencies
  apt: name={{ item }} state=present
  with_items: "{{ docker_dependencies }}"

- name: Install docker GPG key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add docker apt repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main" state=present

- name: Update apt-cache
  apt: update_cache=yes

- name: Install docker package
  apt: name=docker-engine state=present
  notify: Start Docker

- name: Add vagrant user to docker group
  user:
      name: vagrant 
      groups: docker
      append: yes
