---
- name: "Download {{ zmq_full_name }} library"
  get_url:
    url: "{{ zmq_url }}"
    dest: /tmp

- name: "Unarchive downloaded {{ zmq_full_name }} file"
  unarchive:
    src: /tmp/{{ zmq_full_name }}.tar.gz
    dest: /opt
    remote_src: yes

- name: "Install {{ zmq_full_name }} libs"
  shell: "./configure && make -j4 && make install"
  args:
    chdir: "/opt/{{ zmq_full_name }}"

- name: "Get zmq c++ bindings"
  get_url:
    url: "{{ item }}"
    dest: /usr/local/include/
  with_items:
    - https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    - https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq_addon.hpp