---
- name: Check if Wiringpi exists
  stat: path={{ wiringpi_dir }}
  register: wiringpi

- name: Clone wiring pi library
  git:
    clone: yes
    dest: /opt/wiringPi
    repo: "{{ wiringpi_repo }}"
    update: yes
  notify:
    - install wiring pi
  when: not wiringpi.stat.exists